name: Build and test
on:
  workflow_call:

jobs:
  build-and-test:
    name: ${{ matrix.os }}-build-release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            extension: ".exe"
          - os: ubuntu-latest
            triplet: x64-linux
            extension: ""
          - os: macos-12
            triplet: x64-osx
            extension: ""

    steps:
      - uses: actions/checkout@v1

      - name: Setup cmake
        if: runner.os != 'Windows'
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.25.x'

      - name: prepare-windows
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: mingw64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake

      - name: build-windows
        shell: msys2 {0}
        if: runner.os == 'Windows'
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release

      - name: build-unix
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: rename-binary
        run: |
          # cd build
          ls
          mv flexfringe${{ matrix.extension }} flexfringe-${{ matrix.triplet }}${{ matrix.extension}}

      - name: run-tests
        run: ./runtests${{ matrix.extension }} -r junit > testresults-${{ matrix.triplet }}.xml

      - name: publish-test-results-linux
        uses: EnricoMi/publish-unit-test-result-action@v2.14.0
        if: runner.os == 'Linux' && always()
        with:
          check_name: "Unit Test Results (${{ matrix.triplet }})"
          junit_files: "testresults-${{ matrix.triplet }}.xml"

      - name: publish-test-results-other
        uses: EnricoMi/publish-unit-test-result-action/composite@v2.14.0
        if: runner.os != 'Linux' && always()
        with:
          check_name: "Unit Test Results (${{ matrix.triplet }})"
          junit_files: "testresults-${{ matrix.triplet }}.xml"

      - name: upload-binary-artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'flexfringe-${{ matrix.triplet }}'
          path: '${{ runner.workspace }}/FlexFringe/build/flexfringe-${{ matrix.triplet }}${{ matrix.extension}}'
